"""
This type stub file was generated by pyright.
"""

from selenium.webdriver import Chrome as Driver

def chrome_runtime(driver: Driver, run_on_insecure_origins: bool = ..., **kwargs) -> None:
    ...

