"""
This type stub file was generated by pyright.
"""

from selenium.webdriver import Chrome as Driver

def user_agent_override(driver: Driver, user_agent: str = ..., language: str = ..., platform: str = ..., **kwargs) -> None:
    ...

