"""
This type stub file was generated by pyright.
"""

from selenium.webdriver import Chrome as Driver

def webgl_vendor_override(driver: Driver, webgl_vendor: str, renderer: str, **kwargs) -> None:
    ...

