"""
This type stub file was generated by pyright.
"""

from selenium.webdriver import Chrome as Driver
from typing import Any

def evaluationString(fun: str, *args: Any) -> str:
    """Convert function and arguments to str."""
    ...

def evaluateOnNewDocument(driver: Driver, pagefunction: str, *args: str) -> None:
    ...

